# Generated by Django 2.0.6 on 2018-06-14 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('completed', models.BooleanField(verbose_name='completed')),
                ('added_time', models.DateTimeField(default=datetime.datetime(2018, 6, 14, 0, 41, 26, 874948, tzinfo=utc))),
                ('due_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
